version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10
    environment:
      HUGO_ENV: development
      HUGO_VERSION: '0.57.2'
    working_directory: ~/project/

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Install Hugo
          command: |
            mkdir -p bin
            curl -sSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz | tar xzf - -C ./bin/
      - yarn_install
      - run: PATH=~/project/bin:${PATH} yarn build
      - persist_to_workspace:
          paths:
            - ./*
          root: .

  deploy:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: PATH=~/project/bin:${PATH} HUGO_ENV=production yarn build --minify
      - run: yarn deploy --user "bot <bot@manael.org>"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
